import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { Lock, LogOut, ShieldAlert } from 'lucide-react';
import { toast } from 'sonner';

export const MfaChallenge: React.FC = () => {
    const { verifyMfaCode, signOut } = useAuth();
    const [code, setCode] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [trustDevice, setTrustDevice] = useState(false);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (code.length !== 6) {
            setError("Please enter a 6-digit code.");
            return;
        }
        setLoading(true);
        setError(null);
        try {
            await verifyMfaCode(code, trustDevice);
            toast.success("Identity verified successfully!");
        } catch (err: any) {
            console.error("MFA verification error:", err);
            setError(err.message || "Invalid verification code. Please check your authenticator app.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4 relative overflow-hidden">
            {/* Premium background radial gradient */}
            <div className="absolute inset-0 bg-[#0B1020]/[0.025] pointer-events-none" />

            <div className="max-w-md w-full bg-white/80 backdrop-blur-xl border border-slate-200/60 rounded-[2.5rem] p-10 shadow-2xl relative overflow-hidden group">
                <div className="absolute -top-24 -right-24 w-48 h-48 bg-rose-500/10 rounded-full blur-[100px]" />

                <div className="relative z-10 flex flex-col items-center text-center">
                    <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-rose-500/10 border border-rose-500/20 shadow-lg mb-6 text-rose-600">
                        <Lock size={32} className="animate-pulse" />
                    </div>

                    <h1 className="text-2xl font-black text-slate-900 tracking-tight mb-2">Two-Factor Verification</h1>
                    <p className="text-xs font-semibold text-slate-500 max-w-xs mb-8 leading-relaxed">
                        To maintain HIPAA data protection standards, please enter the 6-digit security code generated by your authenticator app.
                    </p>

                    <form onSubmit={handleSubmit} className="w-full space-y-5">
                        <div className="space-y-2">
                            <input
                                type="text"
                                maxLength={6}
                                value={code}
                                onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
                                className="w-full text-center h-14 rounded-2xl border border-slate-200 bg-slate-50 text-xl font-bold tracking-[0.5em] focus:bg-white focus:outline-none focus:ring-4 focus:ring-rose-500/5 focus:border-rose-500/50 transition-all text-slate-800"
                                placeholder="000000"
                                autoFocus
                                required
                            />
                            {error && (
                                <p className="text-xs font-bold text-red-500 pt-1 flex items-center justify-center gap-1.5">
                                    <ShieldAlert size={12} /> {error}
                                </p>
                            )}
                        </div>

                        <div className="flex items-center justify-start gap-2.5 px-1 py-1">
                            <input
                                type="checkbox"
                                id="trustDevice"
                                checked={trustDevice}
                                onChange={(e) => setTrustDevice(e.target.checked)}
                                className="h-4 w-4 rounded border-slate-300 text-rose-600 focus:ring-rose-500 cursor-pointer"
                            />
                            <label htmlFor="trustDevice" className="text-xs font-bold text-slate-500 hover:text-slate-700 cursor-pointer select-none">
                                Trust this device for 90 days
                            </label>
                        </div>

                        <button
                            type="submit"
                            disabled={loading || code.length !== 6}
                            className="w-full h-12 rounded-2xl bg-rose-600 text-white hover:bg-rose-700 disabled:opacity-50 font-bold text-xs uppercase tracking-widest transition-all hover:shadow-lg hover:shadow-rose-500/10 active:scale-95"
                        >
                            {loading ? "Verifying..." : "Verify Session"}
                        </button>
                    </form>

                    <div className="h-px w-full bg-slate-100 my-6" />

                    <button
                        onClick={() => signOut('voluntary')}
                        className="flex items-center justify-center gap-2 text-xs font-bold text-slate-400 hover:text-slate-600 transition-colors uppercase tracking-wider"
                    >
                        <LogOut size={14} />
                        Cancel & Sign Out
                    </button>
                </div>
            </div>
        </div>
    );
};
