import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { useLanguage } from '../context/LanguageContext';
import { OtpInput } from '../components/ui/OtpInput';
import { Lock, LogOut, ShieldAlert, ShieldCheck, ArrowRight, Smartphone } from 'lucide-react';
import { toast } from 'sonner';

export const MfaChallenge: React.FC = () => {
    const { verifyMfaCode, signOut } = useAuth();
    const { language } = useLanguage();
    const [code, setCode] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [trustDevice, setTrustDevice] = useState(false);

    const isEs = language === 'es';

    const handleVerify = async (codeToVerify?: string) => {
        const targetCode = codeToVerify || code;
        if (targetCode.length !== 6) {
            setError(isEs ? "Por favor ingrese un código de 6 dígitos." : "Please enter a 6-digit code.");
            return;
        }
        setLoading(true);
        setError(null);
        try {
            await verifyMfaCode(targetCode, trustDevice);
            toast.success(isEs ? "¡Identidad verificada con éxito!" : "Identity verified successfully!");
        } catch (err: any) {
            console.error("MFA verification error:", err);
            setError(err.message || (isEs ? "Código inválido. Verifique su app autenticadora." : "Invalid verification code. Please check your authenticator app."));
        } finally {
            setLoading(false);
        }
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        handleVerify();
    };

    return (
        <div className="min-h-screen bg-slate-950 flex items-center justify-center p-4 sm:p-6 relative overflow-hidden selection:bg-indigo-500 selection:text-white">
            {/* Ambient Background Blur Glows */}
            <div className="absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-indigo-600/15 rounded-full blur-[140px] pointer-events-none" />
            <div className="absolute bottom-10 right-10 w-80 h-80 bg-violet-600/10 rounded-full blur-[120px] pointer-events-none" />

            <div className="max-w-md w-full bg-slate-900/90 backdrop-blur-2xl border border-slate-800/80 rounded-[2.5rem] p-6 sm:p-9 shadow-[0_25px_60px_-15px_rgba(0,0,0,0.7)] relative overflow-hidden group z-10 animate-in fade-in zoom-in-95 duration-300">
                {/* Top border accent */}
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-36 h-1 bg-gradient-to-r from-transparent via-indigo-500 to-transparent rounded-full opacity-70" />

                <div className="flex flex-col items-center text-center">
                    {/* Security Badge Icon */}
                    <div className="flex size-16 items-center justify-center rounded-2xl bg-indigo-500/10 border border-indigo-500/30 text-indigo-400 shadow-[0_0_25px_rgba(99,102,241,0.2)] mb-5">
                        <Lock size={30} className="stroke-[2.2] animate-pulse" />
                    </div>

                    <h1 className="text-2xl font-black text-white tracking-tight mb-2">
                        {isEs ? "Verificación de 2 Factores" : "Two-Factor Verification"}
                    </h1>
                    <p className="text-xs font-medium text-slate-400 max-w-xs mb-6 leading-relaxed">
                        {isEs 
                            ? "Para garantizar la seguridad e integridad HIPAA de los datos clínicos, ingrese el código de 6 dígitos de su app autenticadora."
                            : "To maintain HIPAA data protection standards, please enter the 6-digit security code generated by your authenticator app."}
                    </p>

                    <form onSubmit={handleSubmit} className="w-full space-y-6">
                        {/* OTP Input Segmented */}
                        <div className="bg-slate-950/70 p-5 rounded-2xl border border-slate-800/80 space-y-3">
                            <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 flex items-center justify-center gap-1.5">
                                <Smartphone size={12} className="text-indigo-400" />
                                {isEs ? "Código Autenticador" : "Authenticator Code"}
                            </label>
                            
                            <div className="py-2">
                                <OtpInput
                                    length={6}
                                    value={code}
                                    onChange={(val) => {
                                        setCode(val);
                                        if (error) setError(null);
                                    }}
                                    disabled={loading}
                                    hasError={Boolean(error)}
                                    autoFocus={true}
                                    onComplete={(completedCode) => handleVerify(completedCode)}
                                />
                            </div>

                            {error && (
                                <p className="text-xs font-bold text-rose-400 flex items-center justify-center gap-1.5 pt-1 animate-bounce">
                                    <ShieldAlert size={14} className="shrink-0" /> {error}
                                </p>
                            )}
                        </div>

                        {/* Custom Trust Device Card Toggle */}
                        <div 
                            onClick={() => setTrustDevice(!trustDevice)}
                            className={`flex items-center justify-between p-3.5 rounded-2xl border transition-all cursor-pointer select-none ${
                                trustDevice 
                                    ? 'bg-indigo-500/10 border-indigo-500/40 text-indigo-200' 
                                    : 'bg-slate-950/40 border-slate-800 text-slate-400 hover:border-slate-700'
                            }`}
                        >
                            <div className="flex items-center gap-3 text-left">
                                <ShieldCheck size={18} className={trustDevice ? 'text-indigo-400' : 'text-slate-500'} />
                                <div className="space-y-0.5">
                                    <p className="text-xs font-bold leading-tight">
                                        {isEs ? "Confiar en este dispositivo" : "Trust this device"}
                                    </p>
                                    <p className="text-[10px] text-slate-500 font-medium">
                                        {isEs ? "Válido por 90 días en este equipo" : "Valid for 90 days on this machine"}
                                    </p>
                                </div>
                            </div>
                            <input
                                type="checkbox"
                                checked={trustDevice}
                                onChange={(e) => setTrustDevice(e.target.checked)}
                                onClick={(e) => e.stopPropagation()}
                                className="size-4 rounded border-slate-700 bg-slate-900 text-indigo-600 focus:ring-indigo-500 focus:ring-offset-slate-900 cursor-pointer accent-indigo-500"
                            />
                        </div>

                        {/* Verify Button */}
                        <button
                            type="submit"
                            disabled={loading || code.length !== 6}
                            className="w-full h-12 rounded-xl bg-gradient-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-400 disabled:opacity-40 text-white font-bold text-xs uppercase tracking-wider transition-all shadow-lg shadow-indigo-600/20 active:scale-98 flex items-center justify-center gap-2"
                        >
                            {loading ? (
                                <>
                                    <div className="size-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                    {isEs ? "Verificando..." : "Verifying..."}
                                </>
                            ) : (
                                <>
                                    {isEs ? "Verificar Sesión" : "Verify Session"}
                                    <ArrowRight size={14} />
                                </>
                            )}
                        </button>
                    </form>

                    <div className="h-px w-full bg-slate-800/80 my-6" />

                    <button
                        type="button"
                        onClick={() => signOut('voluntary')}
                        className="flex items-center justify-center gap-2 text-xs font-bold text-slate-500 hover:text-slate-300 transition-colors uppercase tracking-wider py-1.5 px-3 rounded-lg hover:bg-slate-800/50"
                    >
                        <LogOut size={14} />
                        {isEs ? "Cancelar y Cerrar Sesión" : "Cancel & Sign Out"}
                    </button>
                </div>
            </div>
        </div>
    );
};
