const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');

const envText = fs.readFileSync('C:\\Users\\REINIER\\.gemini\\antigravity\\scratch\\amexzone-notes-bot\\.env', 'utf8');
const env = {};
envText.split('\n').forEach(line => {
    const parts = line.split('=');
    if (parts.length >= 2) {
        env[parts[0].trim()] = parts.slice(1).join('=').trim().replace(/^['"]|['"]$/g, '');
    }
});

const SUPABASE_URL = env.SUPABASE_URL || 'https://toisvwdmscmnogzcpeyj.supabase.co';
const SUPABASE_KEY = env.SUPABASE_SERVICE_ROLE_KEY || env.SUPABASE_ANON_KEY;
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

async function main() {
    console.log("Fetching patient Testthiago Six from Supabase...");
    const { data: patient, error: pErr } = await supabase
        .from('patients')
        .select('*')
        .ilike('full_name', '%Testthiago Six%')
        .single();

    if (pErr) {
        console.error("Error fetching patient:", pErr);
        return;
    }

    console.log(`Found patient: ${patient.full_name} (${patient.emr_id})`);
    
    // The tcm_social_needs contains the clinical details generated by the AI
    const data = patient.tcm_social_needs || {};

    const payload = {
        type: 'TCM_ASSESSMENT',
        patient_emr_id: patient.emr_id || '27510',
        patient_name: patient.full_name,
        patient_dob: patient.dob,
        gender: patient.gender || 'Female',
        ssn: patient.ssn || '',
        phone: patient.phone || '',
        email: patient.email || '',
        address: patient.address || '',
        psych_name: patient.psych_name || 'Dr. Luannys Quesada Carvajal, APRN',
        pcp_name: patient.pcp_name || 'Dr. Jose A. Gonzalez',
        case_manager: patient.case_manager || 'Claudia Leyva',
        assessment_data: {
            ...data,
            // Ensure enjoyable_activities is included
            enjoyable_activities: data.enjoyable_activities || 'Enjoys watching television, listening to music, resting, and short walks.',
            info_providers: [
                { name: patient.full_name, agency: 'Self', relationship: 'Client' },
                { name: patient.psych_name || 'Dr. Luannys Quesada Carvajal, APRN', agency: 'Arc Mental Health Services', relationship: 'Psychiatrist' }
            ],
            // Let's print providers and medications to verify they match our fixes!
            medications_grid: data.medications_grid || [
                { medication: 'Sertraline', dose: '100 mg tablet, PO every morning', physician: 'Dr. Luannys Quesada Carvajal, APRN', purpose: 'Treatment of major depressive disorder' },
                { medication: 'Trazodone', dose: '50 mg HS', physician: 'Dr. Luannys Quesada Carvajal, APRN', purpose: 'Treatment of insomnia' },
                { medication: 'Alprazolam', dose: '0.25 mg PRN', physician: 'Dr. Luannys Quesada Carvajal, APRN', purpose: 'Management of anxiety symptoms' }
            ]
        }
    };

    console.log("Inserting task into public.amexzone_note_tasks...");
    const { data: inserted, error: insertErr } = await supabase
        .from('amexzone_note_tasks')
        .insert({
            note_id: null,
            user_id: patient.user_id,
            patient_name: patient.full_name,
            patient_dob: patient.dob,
            visit_date: new Date().toISOString().split('T')[0],
            note_text: '[TCM_ASSESSMENT]\n' + JSON.stringify(payload),
            status: 'pending'
        })
        .select();

    if (insertErr) {
        console.error("❌ Error inserting task:", insertErr);
    } else {
        console.log("✅ TAREA DE PRUEBA ENCOLADA EXITOSAMENTE:", inserted[0].id);
        console.log("Monitoring task progress...");
        
        let completed = false;
        for (let i = 0; i < 60; i++) {
            await new Promise(r => setTimeout(r, 2000));
            const { data: task, error: tErr } = await supabase
                .from('amexzone_note_tasks')
                .select('status, error_message, result_summary')
                .eq('id', inserted[0].id)
                .single();
                
            if (tErr) {
                console.error("Error monitoring task:", tErr);
                break;
            }
            
            console.log(`Task Status: ${task.status}`);
            if (task.status === 'completed' || task.status === 'failed') {
                completed = true;
                console.log("\n=================== RESULTADOS DE LA TAREA ===================");
                console.log("Status:", task.status);
                if (task.status === 'failed') {
                    console.log("Error Message:", task.error_message);
                } else {
                    console.log("Result Summary:", task.result_summary || 'Task completed successfully without summary.');
                }
                console.log("=========================================================");
                break;
            }
        }
        
        if (!completed) {
            console.log("Task did not complete within timeout.");
        }
    }
}

main();
